CREATE TABLE ARTICLE_SELLY (
ID INT NOT NULL AUTO_INCREMENT ,
PRODUCT_NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

CREATE TABLE PRODUCT_PHOTO_URL(
PRODUCT_PHOTO_ID INT NOT NULL AUTO_INCREMENT,
PRODUCT_ID VARCHAR(255),
PHOTO_URL VARCHAR(255)
);