version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_contain
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:latest
    container_name: mysql_contain
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
    volumes:
      - ./  /mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"