-- create USER_AUTHENTICATE table
CREATE TABLE USER_AUTHENTICATE (
ID int NOT NULL AUTO_INCREMENT  PRIMARY KEY,
USER_NAME VARCHAR(255),
PASSWORD VARCHAR(255),
TOKEN VARCHAR(255)
);

-- INSERT USER AUTHENTICATE DATA
INSERT INTO USER_AUTHENTICATE (USER_NAME, PASSWORD, TOKEN) VALUES ('+84586099640', '123456', '12313DSDASDSD');
--- INSERT SELLY TABLE
CREATE TABLE ARTICLE_SELLY (
ID INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
PRODUCT_NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

CREATE TABLE PRODUCT_PHOTO_URL(
PRODUCT_PHOTO_ID INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
PRODUCT_ID VARCHAR(255),
PHOTO_URL VARCHAR(255)
);